version: "2"

volumes:
  data_mysql_push:
    driver: local
  data_redis_push:
    driver: local


services:

  code_push:
    image: tianon/true
    volumes:
      - ../:/app

#  Container for service
  workspace-push:
    build:
      context: ./php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPUNIT=true
        - INSTALL_COMPOSER=true
    volumes_from:
      - code
    links:
      - web-push
      - db-push:db
      - redis-push:redis
    env_file:
      - base.env
    tty: true
    working_dir: /app
    command: sh -c "php artisan queue:restart && sh"



#  PHP-FPM
  php-push:
    build:
      context: ./php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPUNIT=true
    volumes_from:
      - code
    links:
      - db-push:db
      - redis-push:redis
    env_file:
      - base.env



#  Jobs dispatcher
  worker-push:
    build:
      context: ./php
      args:
        - INSTALL_XDEBUG=true
    volumes_from:
      - code-push
    links:
      - db-push:db
      - redis-push:redis
    env_file:
      - base.env
    working_dir: /app
    restart: always
    command: php artisan queue:work




# nginx
  web-push:
    build:
      context: ./nginx
    volumes_from:
      - code-push
    ports:
      - 8085:80
    links:
      - php-push
    environment:
     - NGINX_HOST=push.in
     - NGINX_PORT=80
     - FPM_HOST=php-push
     - FPM_PORT=9000
    #command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$FPM_HOST $$FPM_PORT' < /etc/nginx/conf.d/sms_service.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"




  db-push:
    image: mysql
    volumes:
      - data_mysql_push:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: push
      MYSQL_USER: push
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret


  redis-push:
    image: redis
    volumes:
      - data_redis_push:/data