FROM php:7.1.3-fpm
MAINTAINER Dmitry Kuzmin rockwith@me.com

RUN DEBIAN_FRONTEND=noninteractive \
	apt-get update;\
	apt-get -y install \
	    mc \
	    software-properties-common \
	    libxml2-dev \
	    php-soap && \


#-------------OTHER_EXT----------------
    apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    libz-dev \
    libjpeg-dev \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev && \
    pecl channel-update pecl.php.net && \
    docker-php-ext-install mcrypt && \
	docker-php-ext-install zip && \
	docker-php-ext-install tokenizer && \
  	docker-php-ext-install pdo_mysql && \
  	docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd && \
    docker-php-ext-install soap

#-------------XDEBUG----------------

ARG INSTALL_XDEBUG=false
RUN if [ ${INSTALL_XDEBUG} = true ]; then \
    # Install the xdebug extension
    pecl install xdebug && \
    docker-php-ext-enable xdebug \
;fi


RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer


#-------------PHPUNIT----------------
ARG INSTALL_PHPUNIT=false
RUN if [ ${INSTALL_PHPUNIT} = true ]; then \
php -r "copy('https://phar.phpunit.de/phpunit.phar', 'phpunit.phar');" && \
    chmod +x phpunit.phar && \
    mv phpunit.phar /usr/local/bin/phpunit \
	;fi

RUN docker-php-ext-configure opcache --enable-opcache \
    && docker-php-ext-install opcache
ADD opcache.ini  /usr/local/etc/php/conf.d/


ADD xdebug.ini /usr/local/etc/php/conf.d/

CMD ["php-fpm"]
EXPOSE 9000
